// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40FjzMYR9PEQSeC3x9eJMlL9GF8xZtpE',
    appId: '1:518730146197:android:fa7000c79603b46772569c',
    messagingSenderId: '518730146197',
    projectId: 'bhoj-ki-khoj',
    databaseURL: 'https://bhoj-ki-khoj-default-rtdb.firebaseio.com',
    storageBucket: 'bhoj-ki-khoj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKIp2qcV8nEs-rvI6H_Si6hTlqTuf_Df8',
    appId: '1:518730146197:ios:282c6e74c4e0934f72569c',
    messagingSenderId: '518730146197',
    projectId: 'bhoj-ki-khoj',
    databaseURL: 'https://bhoj-ki-khoj-default-rtdb.firebaseio.com',
    storageBucket: 'bhoj-ki-khoj.appspot.com',
    iosClientId: '518730146197-ioavtl0824agmigc8l0ir503mfb2htfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhojKiKhoj',
  );
}
