name: bhoj_ki_khoj
description: ""
publish_to: 'none'

version: 1.0.8+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.8.0
  flutter_inappwebview: ^6.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.0.0
  # firebase_messaging: ^10.0.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pwa/splash.html
    - assets/pwa/index.html
    - assets/pwa/offline.html
    - assets/pwa/pages/404.html
    - assets/pwa/pages/
    - assets/pwa/pages/categories/

